version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 211125420613.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=211125420613.dkr.ecr.us-east-1.amazonaws.com/laravel-rds
      
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:latest
      - echo Updating ECS service...

artifacts:
  files:
    - imagedefinitions.json

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
