
version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip3 install awscli
      - cp ./myApp/.env.example ./myApp/.env

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 211125420613.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t laravel .
      - docker tag laravel:latest 211125420613.dkr.ecr.us-east-1.amazonaws.com/laravel:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 211125420613.dkr.ecr.us-east-1.amazonaws.com/laravel:latest
      - aws ecs update-service --cluster laravel --service laravel-service --force-new-deployment

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
